# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a50tftg256-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths E:/labo3/labo3/ip_repo/led_ip_1.0 [current_fileset]
read_vhdl -library xil_defaultlib {
  E:/labo3/labo3/ip_repo/led_ip_1.0/src/lab3_user_logic.vhd
  E:/labo3/labo3/ip_repo/led_ip_1.0/hdl/led_ip_v1_0_S_AXI.vhd
  E:/labo3/labo3/ip_repo/led_ip_1.0/hdl/led_ip_v1_0.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/labo3/labo3/ip_repo/led_ip_1.0/led_ip_v1.0_project/led_ip_v1.0_project.cache/wt [current_project]
set_property parent.project_dir E:/labo3/labo3/ip_repo/led_ip_1.0/led_ip_v1.0_project [current_project]
catch { write_hwdef -file led_ip_v1_0.hwdef }
synth_design -top led_ip_v1_0 -part xc7a50tftg256-1
write_checkpoint led_ip_v1_0.dcp
report_utilization -file led_ip_v1_0_utilization_synth.rpt -pb led_ip_v1_0_utilization_synth.pb
