webtalk_init -webtalk_dir E:\\MicroBlaze_Lab3\\MicroBlaze_Lab3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "di mei 15 17:53:28 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210769010_1777502533_210587611_964" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tavdhlvounc0rhmaqi28p47a4f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1526397756629" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1526397756629"
webtalk_add_data -client sdk -key uid -value "1526397816682" -context "sdk\\\\bsp/1526397816682"
webtalk_add_data -client sdk -key hwid -value "1526397756629" -context "sdk\\\\bsp/1526397816682"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1526397816682"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1526397816682"
webtalk_add_data -client sdk -key uid -value "1526397818258" -context "sdk\\\\application/1526397818258"
webtalk_add_data -client sdk -key hwid -value "1526397756629" -context "sdk\\\\application/1526397818258"
webtalk_add_data -client sdk -key bspid -value "1526397816682" -context "sdk\\\\application/1526397818258"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1526397818258"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1526397818258"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1526397818258"
webtalk_transmit -clientid 2537974022 -regid "210769010_1777502533_210587611_964" -xml E:\\MicroBlaze_Lab3\\MicroBlaze_Lab3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\MicroBlaze_Lab3\\MicroBlaze_Lab3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\MicroBlaze_Lab3\\MicroBlaze_Lab3.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
